[package]
name = "teph_show_scene"
version = "0.2.0"
edition = "2024"

[dependencies]
tephrite_rs = { git = "https://github.com/InsightCenterNoodles/tephrite_rs.git", rev = "5fe7f5ae7f01afd444d9c9c9de08a3ff1b76e23e" }
bevy = "0.18.1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
toml = "0.9"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
